import {
  AwardIcon,
  BabyIcon,
  BanknoteIcon,
  BookOpenIcon,
  BriefcaseIcon,
  BusIcon,
  CarIcon,
  CoffeeIcon,
  CoinsIcon,
  DumbbellIcon,
  EllipsisIcon,
  FilmIcon,
  FuelIcon,
  GiftIcon,
  GraduationCapIcon,
  HandCoinsIcon,
  HandHeartIcon,
  HeartPulseIcon,
  HouseIcon,
  LandmarkIcon,
  type LucideIcon,
  MegaphoneIcon,
  PackageIcon,
  PawPrintIcon,
  PiggyBankIcon,
  PlaneIcon,
  ReceiptIcon,
  ScaleIcon,
  ShirtIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SmartphoneIcon,
  SparklesIcon,
  StoreIcon,
  TrendingUpIcon,
  TruckIcon,
  UsersIcon,
  UtensilsIcon,
  WifiIcon,
  WrenchIcon,
  ZapIcon,
} from "lucide-react"

/** Icons offered for categories; the key is what the database stores. */
export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  utensils: UtensilsIcon,
  coffee: CoffeeIcon,
  bus: BusIcon,
  car: CarIcon,
  fuel: FuelIcon,
  plane: PlaneIcon,
  house: HouseIcon,
  zap: ZapIcon,
  wifi: WifiIcon,
  smartphone: SmartphoneIcon,
  "shopping-bag": ShoppingBagIcon,
  "shopping-cart": ShoppingCartIcon,
  shirt: ShirtIcon,
  "heart-pulse": HeartPulseIcon,
  dumbbell: DumbbellIcon,
  "graduation-cap": GraduationCapIcon,
  "book-open": BookOpenIcon,
  baby: BabyIcon,
  "paw-print": PawPrintIcon,
  gift: GiftIcon,
  film: FilmIcon,
  sparkles: SparklesIcon,
  banknote: BanknoteIcon,
  award: AwardIcon,
  "trending-up": TrendingUpIcon,
  "hand-heart": HandHeartIcon,
  "hand-coins": HandCoinsIcon,
  coins: CoinsIcon,
  "piggy-bank": PiggyBankIcon,
  package: PackageIcon,
  store: StoreIcon,
  users: UsersIcon,
  truck: TruckIcon,
  megaphone: MegaphoneIcon,
  wrench: WrenchIcon,
  landmark: LandmarkIcon,
  briefcase: BriefcaseIcon,
  receipt: ReceiptIcon,
  scale: ScaleIcon,
  ellipsis: EllipsisIcon,
}

export function getCategoryIcon(key: string | null | undefined): LucideIcon {
  return CATEGORY_ICONS[key ?? ""] ?? EllipsisIcon
}
